language: node_js
node_js: "6"

env:
  global:
    - REPO_SLUG=jlopp/bitcoin-core-config-generator
    - secure: "HMvHMoapkGsNgSnvpPybmllu36DocG10pVOuVW9cChWUtcHUfp2ZFZAxzHMtW7m9u6M2BcbyhYKHDcw3wPpvJix71E2ZqYdmmVxzjnDJMzB6GbJvuq/sO4v1yw9Z2U+einjDFLQm9L+RFqCvLiw1qC412urtO7HQ9Hbd6TSgbTnxsw26zk1nZvtpJ9MZiSl7Qn+cneiIy4fFw4WGd0Oqs2tdawmbVcYn0lUXfEIibJJjzbk6lK+ZJD5gDRfy0K3H56G3ERtTd7PGXHGXxuPQ9lSYhxL9MPmt9TnuYDcw+aolkbw2xbXnOmj8LJoPNJiD3CcPvkeEZjzn9mCezuwIg8VsVjFbxsRThCEiUhLOPgTC3EPp3ci/q5WPPLuTE3Sd4dK9xTedFgjYez2Zvx+BD/nXn76Facr1/HpazyjyTHVzVmBmEpn7mdXpmAiBzQMvJRfjr0HLC0KZ60MoSuXEYthyIdGdAhxwI0eZmwhS+zKsXmzb2f+8k9inBHyf8FrCJf6tf77+HvCCJcpieXmIKwklhVFBOW1euLTEWrevSNnB4LcOeK/yhQE56CCw2SEPD4NtfehQ8kdnaXzmEZMDbRCO5QJhjJr/K+EUwAXzri6gFl6v0cth/K7k47SmaB2c705DH6V6aqMEtdkRts/f/3YhqBbCYIWrqQpo4fMXetI="

script:
  - npm run lint
  - npm test
  - npm run build

after_success:
  - ./scripts/deploy-to-gh-pages.sh
